apiVersion: apps/v1
kind: Deployment
metadata:
  name: nager-date
  labels:
    app: nager-date
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nager-date
  template:
    metadata:
      labels:
        app: nager-date
    spec:
      containers:
      - image: nager/nager-date:latest
        name: nager-date
        ports:
        - containerPort: 80
